[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
#base =

# Primary accent color for interactive elements.
primaryColor = "#A0C915"

# Background color for the main content area.
backgroundColor = "#FFF"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#145EB7"

# Color used for almost all text.
textColor = "#101016"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
#font =